name: Keep Streamlit Awake

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Ping Streamlit health endpoint
        shell: bash
        run: |
          set -euo pipefail
          URL="https://predictingloandefault.streamlit.app/_stcore/health"
          for i in {1..3}; do
            CODE=$(curl -fsS -o /dev/null -w "%{http_code}" \
              -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" \
              "$URL" || true)
            echo "HTTP $CODE"
            if [ -n "$CODE" ] && [ "$CODE" -ge 200 ] && [ "$CODE" -lt 400 ]; then
              exit 0
            fi
            echo "Try $i failed; retrying in 5s…"
            sleep 5
          done
          echo "All tries failed"; exit 1

