name: Keep Streamlit Awake

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit the app URL
        run: |
          set -e
          URL="https://predictingloandefault.streamlit.app/"
          for i in {1..3}; do
            curl -sSL --max-time 20 \
              -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36" \
              "$URL" >/dev/null && exit 0 || echo "Try $i failed, retrying..."
            sleep 5
          done
          echo "All tries failed"; exit 1
