name: Keep Streamlit Awake

on:
  schedule:
    - cron: "*/10 * * * *"   # run every 10 minutes
  workflow_dispatch:        # allows manual “Run workflow” from Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Hit the app URL
        run: |
          echo "Pinging Streamlit app…"
          for i in {1..3}; do
            curl -fsSL https://predictingloandefault.streamlit.app/ >/dev/null && { echo "OK"; exit 0; }
            echo "Retry $i…"; sleep 15
          done
          echo "Failed to reach app"; exit 1
