      - name: Hit the app URL
        run: |
          set -e
          URL="https://predictingloandefault.streamlit.app/"

          for i in {1..3}; do
            CODE=$(curl -sS -o /dev/null -w "%{http_code}" \
              -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36" \
              "$URL" || true)
            echo "HTTP $CODE"
            if [ -n "$CODE" ] && [ "$CODE" -lt 400 ]; then
              exit 0
            fi
            echo "Try $i failed, retrying..."
            sleep 5
          done
          echo "All tries failed"; exit 1
